name: CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x
      - name: Restore
        run: dotnet restore CCMediator.slnx
      - name: Build
        run: dotnet build CCMediator.slnx --configuration Release --no-restore
      - name: Test
        run: dotnet test CCMediator.slnx --configuration Release --no-build --collect:"XPlat Code Coverage" --logger trx
